Configuration:
  # Set up
  device: cpu  # 'cuda' or 'cpu'
  seed:   # Set seed
  save_sample_interval: 1   # Save sample every n epochs
  checkpoint_interval: 5  # Save model every n epochs 
  training_mode: alternating  # training mode 'alternating' or 'combined' or 'continuous'
  load_checkpoint: False
  training: True
  # Visualization
  log_wandb: False
  show_training_process: True
  show_training_evolution: True
  generate_data: True
  show_sample: False
Hyperparameter:
  epochs: 25
  batch_size: 32
  # model selector can have only 1 generator at first index
  model_selector: 'gan_generator_1,
                  dcgan_generator_11,
                  classical_discriminator_1, 
                  classical_discriminator_22, 
                  hybrid_quantum_discriminator_11,'
  models:
    gan_generator_1:
      learning_rate: 0.0002
      betas: 0.9, 0.999
      model_class: GAN_Generator # Select Class for model from models.py
      loss_function: BCELoss  # Any Binary Classification Loss
      optimizer: Adam  # Recommend Adam or RMSprop
    dcgan_generator_1:
      learning_rate: 0.0002
      betas: 0.9, 0.999
      model_class: DCGAN_Generator 
      loss_function: BCELoss  
      optimizer: Adam 
    classical_discriminator_1:
      learning_rate: 0.0001
      betas: 0.9, 0.999
      model_class: ClassicalDiscriminator1
      loss_function: BCELoss
      optimizer: Adam
    classical_discriminator_2:
      learning_rate: 0.0001
      betas: 0.9, 0.999
      model_class: ClassicalDiscriminator2
      loss_function: BCELoss
      optimizer: Adam
    hybrid_quantum_discriminator_1:
      learning_rate: 0.0001
      betas: 0.9, 0.999
      model_class: HybridQuantumDiscriminator1
      loss_function: BCELoss
      optimizer: Adam
    quantum_discriminator_1:
      learning_rate: 0.0001
      betas: 0.9, 0.999
      model_class: QuantumDiscriminator1
      loss_function: NLLLoss
      optimizer: Adam